# Generated by Django 3.2 on 2021-08-04 04:20

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0002_auto_20210730_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mytasks',
            name='task_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 4, 4, 20, 22, 110848, tzinfo=utc), verbose_name='Task Date & Time'),
        ),
     
    ]
