# Generated by Django 3.2.6 on 2021-08-17 09:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20210804_0428'),
    ]

    operations = [
        migrations.AddField(
            model_name='mytasks',
            name='task_completed',
            field=models.BooleanField(default=False, verbose_name='Task Completed'),
        ),
        migrations.AlterField(
            model_name='mytasks',
            name='task_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 17, 9, 57, 57, 33760, tzinfo=utc), verbose_name='Task Date & Time'),
        ),
    ]
