# Generated by Django 3.2 on 2021-08-23 10:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20210821_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='mytasks',
            name='task_date',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='mytasks',
            name='task_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 23, 10, 7, 32, 608141, tzinfo=utc), verbose_name='Task Date & Time'),
        ),
        migrations.AlterField(
            model_name='mytasks',
            name='task_time_only',
            field=models.CharField(choices=[('0', '00:00-01:00'), ('1', '01:00-02:00'), ('2', '02:00-03:00'), ('3', '03:00-04:00'), ('4', '04:00-05:00'), ('5', '05:00-06:00'), ('6', '06:00-07:00'), ('7', '07:00-08:00'), ('8', '08:00-09:00'), ('9', '09:00-10:00'), ('10', '10:00-11:00'), ('11', '11:00-12:00'), ('12', '12:00-13:00'), ('13', '13:00-14:00'), ('14', '14:00-15:00'), ('15', '15:00-16:00'), ('16', '16:00-17:00'), ('17', '17:00-18:00'), ('18', '18:00-19:00'), ('19', '19:00-20:00'), ('20', '20:00-21:00'), ('21', '21:00-22:00'), ('22', '22:00-23:00'), ('23', '23:00-00:00')], default='0', max_length=50, verbose_name='Set task time'),
        ),
    ]
