# Generated by Django 3.2.6 on 2021-09-04 05:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20210823_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='mytasks',
            name='taskDate',
            field=models.DateField(blank=True, null=True, verbose_name='Task Date'),
        ),
        migrations.AddField(
            model_name='mytasks',
            name='taskTime',
            field=models.TimeField(blank=True, null=True, verbose_name='Task Time'),
        ),
        migrations.AlterField(
            model_name='mytasks',
            name='task_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 4, 5, 52, 47, 694541, tzinfo=utc), verbose_name='Task Date & Time'),
        ),
    ]
